name: SkyCore
depend: [Libraries]
loadbefore: [Multiverse-Core] # il a besoin de charger le VoidGenerator
version: '1.0'
main: fr.entasia.skycore.Main
commands:
  skycore:

  setspawn:

  masteredit:
    aliases: [buildtoggle]

  isadmin:
    aliases: [adminis]


  bin:
    aliases: [corbeille, poubelle, trash, binaries]

  spawn:

  is:
    aliases: [island, islands, ile, iles]

  rank:


  money:
    aliases: [monnaie, bal, balance]

  eco:
    aliases: [economy, economie]

  baltop:

  pay:
